channels:
  - defaults
dependencies:
  - dask==0.18.1
  - dask-ml==0.6.0
  - distributed==1.22.0
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - nbserverproxy
  - nomkl
  - h5py
  - pip:
    - graphviz
    - seaborn
